### ISSUE TITLE
Please remove me from this repo...

### ISSUE THREAD

**Issue by lesv** [googleapis/google-oauth-java-client#1118]
Hi,

I'm cc'd on lots of emails and bugs on this repo and I don't have it stared.   I also see the Security tab, which I shouldn't.  Could someone remove me.  There is probably a teams entry that's just me. (that's how we did stuff before OSPO took over)

Thanks,

Les

**Comment by arithmetic1728** [comment]
@lesv Hi Les, are you in any googleapis GitHub groups, like yoshi-java, cloud-dpe, etc? I think this info can be found in https://github.com/ main page, the bottom left corner `Your teams` section. If so, you can click the team then click `Leave team`.

**Comment by clundin25** [comment]
Hi @lesv I cannot see you in any team or organization associated with this repo. Are you subscribed as a watcher?

**Comment by clundin25** [comment]
I'm going to close this but please feel free to re-open if you need further help !
