### ISSUE TITLE
mvn install broken

### ISSUE THREAD

**Issue by elharo** [googleapis/google-oauth-java-client#216]
The check plugin appears to be objecting to API changes. Should this really block `mvn install`?

[INFO] --- clirr-maven-plugin:2.6:check (default) @ google-oauth-client ---
[INFO] Comparing to version: 1.19.0
[ERROR] 7006: com.google.api.client.auth.oauth2.AuthorizationCodeRequestUrl: Return type of method 'public com.google.api.client.http.GenericUrl clone()' has been changed to java.lang.Object
[ERROR] 7006: com.google.api.client.auth.oauth2.AuthorizationCodeRequestUrl: Return type of method 'public java.lang.Object clone()' has been changed to com.google.api.client.http.GenericUrl
[ERROR] 7006: com.google.api.client.auth.oauth2.AuthorizationCodeRequestUrl: Return type of method 'public com.google.api.client.http.GenericUrl set(java.lang.String, java.lang.Object)' has been changed to com.google.api.client.util.GenericData
[ERROR] 7006: com.google.api.client.auth.oauth2.AuthorizationCodeRequestUrl: Return type of method 'public com.google.api.client.util.GenericData set(java.lang.String, java.lang.Object)' has been changed to com.google.api.client.http.GenericUrl
[ERROR] 7006: com.google.api.client.auth.oauth2.AuthorizationCodeResponseUrl: Return type of method 'public com.google.api.client.util.GenericData clone()' has been changed to java.lang.Object
[ERROR] 7006: com.google.api.client.auth.oauth2.AuthorizationCodeResponseUrl: Return type of method 'public java.lang.Object clone()' has been changed to com.google.api.client.util.GenericData
[ERROR] 7006: com.google.api.client.auth.oauth2.AuthorizationRequestUrl: Return type of method 'public com.google.api.client.util.GenericData clone()' has been changed to java.lang.Object
[ERROR] 7006: com.google.api.client.auth.oauth2.AuthorizationRequestUrl: Return type of method 'public java.lang.Object clone()' has been changed to com.google.api.client.util.GenericData
[ERROR] 7006: com.google.api.client.auth.oauth2.BrowserClientRequestUrl: Return type of method 'public com.google.api.client.http.GenericUrl clone()' has been changed to java.lang.Object
[ERROR] 7006: com.google.api.client.auth.oauth2.BrowserClientRequestUrl: Return type of method 'public java.lang.Object clone()' has been changed to com.google.api.client.http.GenericUrl
[ERROR] 7006: com.google.api.client.auth.oauth2.BrowserClientRequestUrl: Return type of method 'public com.google.api.client.http.GenericUrl set(java.lang.String, java.lang.Object)' has been changed to com.google.api.client.util.GenericData
[ERROR] 7006: com.google.api.client.auth.oauth2.BrowserClientRequestUrl: Return type of method 'public com.google.api.client.util.GenericData set(java.lang.String, java.lang.Object)' has been changed to com.google.api.client.http.GenericUrl
[ERROR] 7006: com.google.api.client.auth.oauth2.TokenErrorResponse: Return type of method 'public com.google.api.client.util.GenericData clone()' has been changed to java.lang.Object
[ERROR] 7006: com.google.api.client.auth.oauth2.TokenErrorResponse: Return type of method 'public java.lang.Object clone()' has been changed to com.google.api.client.util.GenericData
[ERROR] 7006: com.google.api.client.auth.oauth2.TokenResponse: Return type of method 'public com.google.api.client.util.GenericData clone()' has been changed to java.lang.Object
[ERROR] 7006: com.google.api.client.auth.oauth2.TokenResponse: Return type of method 'public java.lang.Object clone()' has been changed to com.google.api.client.util.GenericData
[ERROR] 7006: com.google.api.client.auth.openidconnect.IdToken$Payload: Return type of method 'public com.google.api.client.json.GenericJson clone()' has been changed to java.lang.Object
[ERROR] 7006: com.google.api.client.auth.openidconnect.IdToken$Payload: Return type of method 'public java.lang.Object clone()' has been changed to com.google.api.client.json.GenericJson
[ERROR] 7006: com.google.api.client.auth.openidconnect.IdToken$Payload: Return type of method 'public com.google.api.client.json.GenericJson set(java.lang.String, java.lang.Object)' has been changed to com.google.api.client.util.GenericData
[ERROR] 7006: com.google.api.client.auth.openidconnect.IdToken$Payload: Return type of method 'public com.google.api.client.util.GenericData set(java.lang.String, java.lang.Object)' has been changed to com.google.api.client.json.GenericJson
[ERROR] 7006: com.google.api.client.auth.openidconnect.IdTokenResponse: Return type of method 'public com.google.api.client.json.GenericJson clone()' has been changed to java.lang.Object
[ERROR] 7006: com.google.api.client.auth.openidconnect.IdTokenResponse: Return type of method 'public java.lang.Object clone()' has been changed to com.google.api.client.json.GenericJson
[ERROR] 7006: com.google.api.client.auth.openidconnect.IdTokenResponse: Return type of method 'public com.google.api.client.json.GenericJson set(java.lang.String, java.lang.Object)' has been changed to com.google.api.client.util.GenericData
[ERROR] 7006: com.google.api.client.auth.openidconnect.IdTokenResponse: Return type of method 'public com.google.api.client.util.GenericData set(java.lang.String, java.lang.Object)' has been changed to com.google.api.client.json.GenericJson
[INFO] -------

**Comment by ajaaym** [comment]
@elharo mvn install works fine on latest version. I am closing this for now. Please reopen if this is still an issue.
