### ISSUE TITLE
OAuthParameters uses hard-coded path encoding scheme via GenericUrl

### ISSUE THREAD

**Issue by wonderfly** [googleapis/google-oauth-java-client#22]
_From [tra...@circutus.com](https://code.google.com/u/118339485908407033764/) on January 10, 2012 09:59:45_

Version of google-oauth-java-client? 1.6.0-beta

Java environment? App Engine Describe the problem. The problem is that the Dropbox API uses OAuth 1.0, but it expects all http requests to format URL's according to the following encoding (notice the forward-slash, which is needed, because we are creating URL's which point to Dropbox resources),

```
new PercentEscaper("-_.*/", false);
```

com.google.api.client.auth.oauth.OAuthParameters creates an instance of com.google.api.client.http.GenericUrl in the computeSignature method. This is a problem for me, because GenericUrl performs path encoding effectively using,

```
new PercentEscaper("-_.!~*'()@:$&,;=", false);
```

The problems occur when something like a parentheses is in the URL, and Dropbox will immediately reject the request. I can not use the Dropbox Java API, because I'm using App Engine and hence URLFetch. How would you expect it to be fixed? My short term solution has been to completely copy OAuthParameters and change one line of code to use a subclass of GenericUrl in the computeSignature function.

Instead of creating an instance of GenericUrl using the default constructor GenericUrl(), would it work to instead call GenericUrl.clone() on the requestUrl argument and then remove the parts of the URL needed for "normalization" as it is currently being done? Subclasses of GenericUrl could override clone() and that should suffice. I have created a related case for google-http-java-client, https://code.google.com/p/google-http-java-client/issues/detail?id=58 Also, why not remove the final keyword from OAuthParameters? If all else fails, we can then override some of its functions.

_Original issue: http://code.google.com/p/google-oauth-java-client/issues/detail?id=22_

**Comment by westarle** [comment]
Closing this old issue.  Please feel free to reopen if needed.
