### ISSUE TITLE
Google OAuth: Desktop.isDesktopSupported() always returns false

### ISSUE THREAD

**Issue by VaishaliPawar15** [googleapis/google-oauth-java-client#228]
#### Environment details

- OS: Windows 10(tried with Ubuntu as well)
- Java version:1.8.0
- google-oauth-java-client version:1.23.0(tried with 1.25.0 as well)

### External references such as API reference guides used
Used Google OAuth client libraries available on https://github.com/google/google-api-java-client-samples/tree/master/oauth2-cmdline-sample

#### Steps to reproduce
1. Call to AuthorizationCodeInstalledApp to create credentials using below code
        new AuthorizationCodeInstalledApp(flow, localServerReceiver).authorize("user");
2.  In AuthorizationCodeInstalledApp class, inside browse(url) method, 
     Desktop.isDesktopSupported() always returns false due to which its not hitting user consent screen 
     using default browser.

#### Stacktrace
Logs in Console:
Please open the following address in your browser:
  https://accounts.google.com/o/oauth2/auth?client_id=abc&redirect_uri=http://localhost:8080/Callback&response_type=code&scope=https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email

#### Any additional information below
spring boot + maven +REST  application
Once application calls AuthorizationCodeInstalledApp to create Credentials object, its not redirecting to user consent screen on default browser instead ask to open the link in the browser.
Thanks!

**Comment by chingor13** [comment]
`Desktop.isDesktopSupported()` is a built-in Java AWT function. Is this actually running in a desktop environment?
