### ISSUE TITLE
Upgrade jetty version

### ISSUE THREAD

**Issue by chingor13** [googleapis/google-oauth-java-client#233]
See #172.

Ensure that we can upgrade this (internal dependencies).

**Comment by thejeff77** [comment]
Please do this. We need jetty 9.4.11 with Java 8.

**Comment by Danielramn1984** [comment]
Daniel Ramos Navarro
RFC RAND840816AW0
CIF18010124845

**Comment by Danielramn1984** [comment]
Bbvabancomer
Clave interbancaria:012180015539350001

**Comment by GuiSim** [comment]
Another reason:
https://snyk.io/vuln/SNYK-JAVA-ORGMORTBAYJETTY-32091
