### ISSUE TITLE
ID Token verification: cached public keys

### ISSUE THREAD

**Issue by samu** [googleapis/google-oauth-java-client#248]
The docs state [here](https://github.com/googleapis/google-oauth-java-client/blob/2d07a2fdabd340b64e7252a41f2d2eff70821d69/google-oauth-client/src/main/java/com/google/api/client/auth/openidconnect/IdTokenVerifier.java#L131) that the library "verifies that the given ID token is valid using the cached public keys.". 

My interpretation of this is, that the token signature validity is checked using a given public key. When i look at the implementation i can't see any code related to signature verification. Am i missing something, or is it correct that this library is not doing signature verification?

**Comment by zhumin8** [comment]
See code [here](https://github.com/googleapis/google-oauth-java-client/blob/a9a062ef8665495055571534b9fff4fcc630c8ad/google-oauth-client/src/main/java/com/google/api/client/auth/openidconnect/IdTokenVerifier.java#L284) and [here](https://github.com/googleapis/google-oauth-java-client/blob/a9a062ef8665495055571534b9fff4fcc630c8ad/google-oauth-client/src/main/java/com/google/api/client/auth/openidconnect/IdTokenVerifier.java#L321) for signature verification logic.
