### ISSUE TITLE
RefreshToken is null so I can't authenticate to interact google photo by google java client library

### ISSUE THREAD

**Issue by hoangdangduy** [googleapis/google-oauth-java-client#249]
#### Environment details

- OS: Window 10
- Java version: 1.8.0_191
- google-oauth-client-java6:1.23.0:

#### Steps to reproduce

1. Clone and run project at https://github.com/google/java-photoslibrary in PC 1
2. Copy project in PC1 to PC2 and run.
3. Run again project and was throw message about refreshToken is null although I still receive accessToken

Below is image when I debug.

![qa](https://user-images.githubusercontent.com/8912039/52757641-01528d80-3038-11e9-87cf-16b5c2e1c641.png)

and image when throw message

![message](https://user-images.githubusercontent.com/8912039/52757457-4fb35c80-3037-11e9-9faf-c8a327084d9f.png)

**Comment by meredithslota** [comment]
I don't have the correct permissions to move this issue to that repo, but I suspect if this is still happening for you, you should file an issue here: https://github.com/google/java-photoslibrary/issues — there's an older issue there already re: authorization issues, but I'm not sure if it's the same one: https://github.com/google/java-photoslibrary/issues/2
