### ISSUE TITLE
Replacement library?

### ISSUE THREAD

**Issue by bootstraponline** [googleapis/google-oauth-java-client#251]
With `google-oauth-java-client` being deprecated, is there an official replacement? https://github.com/googleapis/google-auth-library-java is the closest I could find.

Thanks.

**Comment by chingor13** [comment]
This entire library is not being deprecated. The general OAuth implementations will remain, however, the Google API-specific authentication classes are now marked as deprecated in favor of https://github.com/googleapis/google-auth-library-java. We do not want to maintain 2 separate implementations of Application Default Credentials and other Google-specific auth mechanisms. For compatibility with google-http-client, see: https://github.com/googleapis/google-auth-library-java#using-credentials-with-google-http-client
