### ISSUE TITLE
HttpServer artifact in addition to Jetty

### ISSUE THREAD

**Issue by ericraskin** [googleapis/google-oauth-java-client#434]
What the problem is:

As reported in #397, the 8.2 version of Jetty included in the google-oauth-client-jetty artifact is incompatible with newer versions of Jetty.  Proposed upgrades to Jetty 9.4 require evaluation.  It was suggested that an HttpServer implementation might be better than upgrading Jetty.

**Describe the solution you'd like**
I would like a new artifact google-oauth-client-httpserver created.  I have already written the code, but it is currently under the jetty artifact, which causes confusion.

**Describe alternatives you've considered**
Upgrading Jetty to 9.4 is under consideration, but both options may be the best solution (upgrade Jetty AND implement an HttpServer version).

**Comment by zhumin8** [comment]
done in https://github.com/googleapis/google-oauth-java-client/pull/433. Closing.
