### ISSUE TITLE
Parallel build is not threadsafe

### ISSUE THREAD

**Issue by elharo** [googleapis/google-oauth-java-client#435]
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe in Google App Engine extensions to the Google OAuth Client Library for Java.:
[WARNING] org.codehaus.mojo:clirr-maven-plugin:2.8
[WARNING] org.apache.maven.plugins:maven-project-info-reports-plugin:3.0.0
[WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
[WARNING] *****************************************************************

**Comment by ksatwara** [comment]
@elharo I tested it many times but didn't find that warning message. Moreover I research on that plugins org.codehaus.mojo:clirr-maven-plugin:2.8 is thread safe and updated with latest version. you can find the link here. https://www.mojohaus.org/clirr-maven-plugin/apidocs/org/codehaus/mojo/clirr/HelpMojo.html.  More over org.apache.maven.plugins:maven-project-info-reports-plugin:3.0.0 is also latest updated plugin of maven for report generation.   still you find the issue please describe here with more description and clarification.
