### ISSUE TITLE
FileCredentialStore failing on Windows

### ISSUE THREAD

**Issue by wonderfly** [googleapis/google-oauth-java-client#55]
_From [yan...@google.com](https://code.google.com/u/111815493751521097215/) on October 09, 2012 05:21:35_

Version of google-oauth-java-client (e.g. 1.5.0-beta)? http://javadoc.google-oauth-java-client.googlecode.com/hg/1.11.0-beta/com/google/api/client/extensions/java6/auth/oauth2/FileCredentialStore.html https://groups.google.com/forum/?fromgroups=#!topic/google-api-java-client/HQzgKGyAMOU Java environment (e.g. Java 6, Android 2.3, App Engine)? Windows.  Possibly others? Describe the problem. We're getting multiple reports of FileCredentialStore failing to set file permissions, throwing an IOException, and therefore not working at all. How would you expect it to be fixed? Need to investigate the most appropriate fix.  One option is to simply log a warning instead of throwing an IOException.

_Original issue: http://code.google.com/p/google-oauth-java-client/issues/detail?id=55_

**Comment by Subrata-cisco** [comment]
What we need the Input stream from  the Json file, which we can get by 
Path path = Paths.get("E:\\Subrata\\developement\\mywork\\everify\\secret.json");
       SeekableByteChannel sbc = Files.newByteChannel(path);
       InputStream inn = Channels.newInputStream(sbc);

Then call  GoogleClientSecrets clientSecrets =
            GoogleClientSecrets.load(JSON_FACTORY, new InputStreamReader(inn));

And all done for Windows testing !!
