### ISSUE TITLE
Missing plugin versions

### ISSUE THREAD

**Issue by elharo** [googleapis/google-oauth-java-client#597]
Warning:  
Warning:  Some problems were encountered while building the effective model for com.google.oauth-client:google-oauth-client-bom:pom:1.31.5-SNAPSHOT
Warning:  'build.plugins.plugin.version' for org.apache.maven.plugins:maven-site-plugin is missing. @ line 114, column 15
Warning:  'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ line 108, column 15
Warning:  
Warning:  It is highly recommended to fix these problems because they threaten the stability of your build.
Warning:  
Warning:  For this reason, future Maven versions might no longer support building such malformed projects.
Warning:

**Comment by TimurSadykov** [comment]
fixed with #713
