### ISSUE TITLE
OAuthHmacSigner only supports HMAC-SHA1 (no ability to use HMAC-SHA256 which is required by NetSuite)

### ISSUE THREAD

**Issue by svonduhn** [googleapis/google-oauth-java-client#702]
Description:
As a NetSuite integration developer, I would like to be able to use HMAC-SHA256, so that I can connect to Netsuite when HMAC-SHA1 is deprecated after August 2021.

Solution:
I would like to have the ability to sign OAuth 1.0 requests using HMAC-SHA256.

Other Information:
As the signature method is hard-coded in the OAuthHmacSigner class, the only way to support this would be a new signer class, or a code change to make the signature method configurable.

Additional Information:
NetSuite, a major cloud-based service and ERP, will stop allowing any connections made using HMAC-SHA1 after their next release in August 2021 (exact date TBD).  As such, I would like to have the ability to switch to HMAC-SHA256 as a signature method, so there will be no interruptions in any integrations using this library.

**Comment by inalef** [comment]
hey folks, I see this is almost wrapped up. Do you have an ETA for its release? Thanks in advance.

**Comment by TimurSadykov** [comment]
> hey folks, I see this is almost wrapped up. Do you have an ETA for its release? Netsuite has already deprecated the use of SHA-1. Thanks in advance.

Hey, yes, it is close. Let's target next week for a release.
