### ISSUE TITLE
IdTokenVerifier does not verify the signature of ID Token

### ISSUE THREAD

**Issue by tamjidrahat** [googleapis/google-oauth-java-client#786]
https://github.com/googleapis/google-oauth-java-client/blob/5c202d654a33f6113de6151d383b8d0f88fab14b/google-oauth-client/src/main/java/com/google/api/client/auth/openidconnect/IdTokenVerifier.java#L152

The _verify_ method in _IdTokenVerifier_ does not validate the signature before verifying the claims (e.g., _iss_, _aud_, etc.). This is also a violation of the ID Token Validation steps mentioned in the current OpenID Connect Spec (https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation). 

The spec requires to validate the _signature_ of ID token for apps that cannot guarantee TLS communication, which is the case for this library. This library initiates a local server that can run on any client machine without TLS support. So, it is critical to validate the signature, before trusting the claims of an ID token, which can be received from a malicious service provider. 

Thanks.

**Comment by lesv** [comment]
@silvolu FYI

**Comment by TimurSadykov** [comment]
The issue confirmed, investigating the best way to fix it

**Comment by TimurSadykov** [comment]
fix in progress

**Comment by TimurSadykov** [comment]
fix ETA Mar 1st, dropping priority according to definitions.
